# Generated by Django 3.1.3 on 2020-11-03 07:07
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("blog", "0005_auto_20201103_0424"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetailpage",
            name="blog_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="blog image",
            ),
        ),
    ]
