# Generated by Django 3.1.2 on 2020-10-16 13:44
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailcore", "0052_pagelogentry"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogdetailpage",
            name="custom_title",
        ),
        migrations.AddField(
            model_name="blogdetailpage",
            name="content",
            field=wagtail.core.fields.RichTextField(
                null=True, verbose_name="blog content"
            ),
        ),
        migrations.AlterField(
            model_name="blogdetailpage",
            name="description",
            field=wagtail.core.fields.RichTextField(
                null=True, verbose_name="blog description"
            ),
        ),
        migrations.DeleteModel(
            name="BlogListingPage",
        ),
    ]
