# Generated by Django 3.1.2 on 2020-10-17 00:18
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20201016_1344"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogdetailpage",
            name="description",
        ),
    ]
