# Generated by Django 3.1.2 on 2020-10-17 01:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blogdetailpage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetailpage",
            name="blog_category",
            field=models.SmallIntegerField(
                choices=[
                    (0, "National"),
                    (1, "International"),
                    (2, "Divers"),
                    (3, "Believe it or no"),
                    (4, "Culture"),
                    (5, "Opinion and the other opinion"),
                    (6, "Caricature"),
                    (7, "Videos"),
                ],
                verbose_name="blog category",
            ),
        ),
    ]
