# Generated by Django 3.1.3 on 2020-11-03 04:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediasettings",
            name="facebook",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook URL"),
        ),
        migrations.AlterField(
            model_name="socialmediasettings",
            name="twitter",
            field=models.URLField(blank=True, null=True, verbose_name="Twitter URL"),
        ),
        migrations.AlterField(
            model_name="socialmediasettings",
            name="youtube",
            field=models.URLField(
                blank=True, null=True, verbose_name="YouTube Channel URL"
            ),
        ),
    ]
